### ISSUE TITLE
selectionStart / selectionEnd are always 0

### ISSUE THREAD

**Issue by urakozz** [react-component/input#62]
After this change (most likely) https://github.com/react-component/input/pull/54, which came into effect with antd 5.12.3, `onchange` event from the input always has selectionStart / selectionEnd properties set to 0 instead of the actual numbers

We have custom input processing (related to the currency formatting), which worked perfectly for the past 6 years until this change.

Would it be possible to have a look into this issue?

**Comment by SleepWalker** [comment]
Faced the same issue with custom phone number input. Event handler need the actual DOM node to handle cursor position.

`rc-input` creates a copy or original DOM node here https://github.com/react-component/input/blob/master/src/utils/commonUtils.ts#L60-L75. If you'll try to manipulate with that node it won't be reflected on the original node because it's just a copy that even wasn't inserted in DOM and of course it has zero cursor position.

As a temporary solution I using ref and patch the event back:

```tsx
const inputRef = React.useRef<InputRef>(null);

return (
  <Input onChange={(event) => {
    const currentTarget = inputRef.current!.input;

    event = Object.create(event, {
      target: { value: currentTarget },
      currentTarget: { value: currentTarget },
    });

   handleChange(event);
  }} />
);
```

**Comment by afc163** [comment]
@yyz945947732 Look at this issue.

**Comment by 0307kwon** [comment]
we have same issue... 😢

**Comment by afc163** [comment]
@yyz945947732 ping~

**Comment by afc163** [comment]
@yyz945947732

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/input/pull/65
